name: Copy Website Files
on:
  push:
    branches:
      - blog
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build Files
        uses: actions/checkout@v4
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: master
          folder: Deploy
          target-folder: docs